### ISSUE TITLE
Can‘t pass the portal.

### ISSUE THREAD

**Issue by decaylong** [ChanceSD/AncientGates#8]
Output this things:

[21:34:49] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to AncientGates v2.0.6
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:KCauldron-1.7.10-2.1403.1.54]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:KCauldron-1.7.10-2.1403.1.54]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:KCauldron-1.7.10-2.1403.1.54]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:KCauldron-1.7.10-2.1403.1.54]
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:359) [nh.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(C03PacketPlayer.java:234) [jf.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.build()Lguava10/com/google/common/cache/Cache;
    at org.mcteam.ancientgates.util.TeleportUtil.<clinit>(TeleportUtil.java:55) ~[?:?]
    at org.mcteam.ancientgates.listeners.PluginMovementListener.onPlayerMove(PluginMovementListener.java:104) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:KCauldron-1.7.10-2.1403.1.54]
    ... 13 more

**Comment by decaylong** [comment]
On cauldron-1.7.10-2.1403.1.54-server

**Comment by decaylong** [comment]
OH, and this: 

[21:34:56] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to AncientGates v2.0.6
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:KCauldron-1.7.10-2.1403.1.54]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:KCauldron-1.7.10-2.1403.1.54]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:KCauldron-1.7.10-2.1403.1.54]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:KCauldron-1.7.10-2.1403.1.54]
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:359) [nh.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(C03PacketPlayer.java:144) [je.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.mcteam.ancientgates.util.TeleportUtil
    at org.mcteam.ancientgates.listeners.PluginMovementListener.onPlayerMove(PluginMovementListener.java:104) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:KCauldron-1.7.10-2.1403.1.54]
    ... 13 more

**Comment by decaylong** [comment]
always output " Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.mcteam.ancientgates.util.TeleportUtil "

**Comment by AliensHive** [comment]
This plugin is for bukkit/spigot 1.8+

**Comment by decaylong** [comment]
I thought it can works with 1.7.10.
 :( 
![qq 20160118232606](https://cloud.githubusercontent.com/assets/6150778/12395233/6a0e3486-be3b-11e5-8e0e-ee0ccd9624ee.png)

**Comment by sgdc3** [comment]
Why did you close the issue?

**Comment by sgdc3** [comment]
@decaylong

**Comment by sgdc3** [comment]
keep it open, this would be a nice enhancement ;)

**Comment by decaylong** [comment]
Cuz I thought you guys dont want to support 1.7.x, but I was wrong. :)
